language: go

go:
  - 1.6.2
  - tip

install:
  - go get github.com/joushou/qp
  - go get github.com/chzyer/readline
  - go get gopkg.in/alecthomas/kingpin.v2

script:
  - go test ./... -race 
  - go build -o ramfs_bin github.com/joushou/qptools/ramfs
  - go build -o exportfs_bin github.com/joushou/qptools/exportfs
  - go build -o cli_bin github.com/joushou/qptools/cli
