language: go

go:
  - 1.6.2
  - tip

install:
  - go get github.com/joushou/qp
  - go get github.com/chzyer/readline
  - go get github.com/alecthomas/kingpin

script:
  - test() { go test "${1}" -coverprofile=o.txt -covermode=atomic -race && (if [ -e o.txt ]; then cat o.txt >> coverage.txt; rm o.txt; fi; true)}
  - test github.com/joushou/qptools/fileserver/trees
  - test github.com/joushou/qptools/fileserver
  - test github.com/joushou/qptools/client
  - go build -o ramfs_bin github.com/joushou/qptools/cmd/ramfs
  - go build -o exportfs_bin github.com/joushou/qptools/cmd/exportfs
  - go build -o 9pc_bin github.com/joushou/qptools/cmd/9pc

notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)