language: go

go:
  - 1.6.2
  - tip

install:
  - go get github.com/joushou/qp
  - go get github.com/chzyer/readline
  - go get github.com/alecthomas/kingpin

script:
  - go test ./... -race 
  - go build -o ramfs_bin github.com/joushou/qptools/cmd/ramfs
  - go build -o exportfs_bin github.com/joushou/qptools/cmd/exportfs
  - go build -o 9pc_bin github.com/joushou/qptools/cmd/9pc
