language: go

go:
  - 1.6.2
  - tip

install:
  - go get github.com/joushou/qp
  - go get github.com/chzyer/readline
  - go get gopkg.in/alecthomas/kingpin.v2

script:
  - go test github.com/joushou/qptools/fileserver/trees -coverprofile=coverage_fileserver_trees.txt -race
  - go test github.com/joushou/qptools/fileserver -coverprofile=coverage_fileserver.txt -race
  - go test github.com/joushou/qptools/client -coverprofile=coverage_client.txt -race
  - go build -o ramfs_bin github.com/joushou/qptools/ramfs
  - go build -o exportfs_bin github.com/joushou/qptools/exportfs
  - go build -o cli_bin github.com/joushou/qptools/cli

after_success:
  - bash <(curl -s https://codecov.io/bash)